<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>4dc257d3-4957-41a9-a8ed-504f6d9514bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id=':Rjpl6:']/footer/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e58259c-787f-4643-8b59-f3faf068664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-text</value>
      <webElementGuid>baaff131-e4d9-4bb5-b598-43788edc7d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إغلاق</value>
      <webElementGuid>fdee842d-de6f-4514-bcb5-3e769d71a739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:Rjpl6:&quot;)/footer[@class=&quot;flex flex-row gap-2 px-6 py-4 justify-end CustomModal__footer beta-banner__footer&quot;]/div[@class=&quot;CustomModal__footer__button-group beta-banner__button-group&quot;]/div[@class=&quot;CustomModal__footer__button&quot;]/button[@class=&quot;z-0 group relative inline-flex items-center justify-center box-border appearance-none select-none whitespace-nowrap font-normal subpixel-antialiased overflow-hidden tap-highlight-transparent outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 px-4 min-w-20 h-10 text-small gap-2 rounded-medium [&amp;>svg]:max-w-[theme(spacing.8)] !transition-none data-[pressed=true]:scale-100 bg-default text-default-foreground data-[hover=true]:opacity-hover beta-banner__button-primary button--reset button--size__medium button--type__primary&quot;]/span[@class=&quot;button-text&quot;]</value>
      <webElementGuid>5b82f0dc-16bc-4781-a31c-5598f5b5d7fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id=':Rjpl6:']/footer/div/div[2]/button/span</value>
      <webElementGuid>5ad1fd3b-905a-414e-bee7-a0e547b7ab91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كن أول من يجرب الميزات الجديدة، وشاركنا رأيك. نشكرك لمساعدتنا على تحسين موقعنا.'])[1]/following::span[1]</value>
      <webElementGuid>02a6081c-e3c7-40c3-a3da-f29f76b09851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إصدار تجريبي'])[1]/following::span[2]</value>
      <webElementGuid>0664658a-2579-4372-aa1e-0b712c55c233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إغلاق']/parent::*</value>
      <webElementGuid>68d27659-f7e6-4fd3-bdc7-2cc8b594c3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/footer/div/div[2]/button/span</value>
      <webElementGuid>cc185327-3510-4f11-b5b4-ac881227e995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'إغلاق' or . = 'إغلاق')]</value>
      <webElementGuid>c93753fc-5e0f-47db-870c-5b72fd37aeb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
